# IPv4 port the server should listen to.
server-port=19132
# Maximum transmission unit for RakNet.
raknet-mtu=1024
# The maximum number of players that can play on the server.
max-players=10
# If true all connected players must be authenticated.
online-mode=true
# Allowed values: zlib, snappy.
compression-algorithm=zlib
# Smallest payload size to compress.
compression-threshold=1
# Maximum chunk view distance players can request.
max-view-distance=32
# Chunk distance around players where entities are ticked.
simulation-distance=4
# World provider type.
world-provider=leveldb
# Path to world data.
world-path=worlds/world
# Identifier of the default world.
default-world=world
# Directory where plugin DLLs are loaded from.
plugins-directory=plugins
world-scheduler-debug=false